/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controlers.CtrlLecon;
import Controlers.CtrlMoniteur;
import Tools.ModelJTable;

/**
 *
 * @author ninou
 */
public class FrmAdminMoniteurPlanning extends javax.swing.JFrame {

    ModelJTable mdl;
    CtrlLecon ctrlLecon;
    CtrlMoniteur ctrlMoniteur;
            
    /**
     * Creates new form FrmMoniteurPlanning
     */
    public FrmAdminMoniteurPlanning() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdminPlanningMoniteur = new javax.swing.JTable();
        lblChoisirMoniteur = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAdminChoisirMoniteur = new javax.swing.JTable();
        lblPlanningMoniteur = new javax.swing.JLabel();
        lblTitreMoniteur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblAdminPlanningMoniteur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblAdminPlanningMoniteur);

        lblChoisirMoniteur.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblChoisirMoniteur.setText("Choissisez un moniteur :");

        tblAdminChoisirMoniteur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblAdminChoisirMoniteur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAdminChoisirMoniteurMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAdminChoisirMoniteur);

        lblPlanningMoniteur.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPlanningMoniteur.setText("Voici son planning :");

        lblTitreMoniteur.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitreMoniteur.setText("Voir le planning d'un moniteur");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(lblChoisirMoniteur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPlanningMoniteur)
                .addGap(162, 162, 162))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitreMoniteur)
                .addGap(450, 450, 450))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitreMoniteur)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChoisirMoniteur)
                    .addComponent(lblPlanningMoniteur))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(199, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ctrlMoniteur = new CtrlMoniteur();
        ctrlLecon = new CtrlLecon();
        mdl = new ModelJTable();
        
        mdl.loadDatasAllMoniteur(ctrlMoniteur.GetAllMoniteur());
        tblAdminChoisirMoniteur.setModel(mdl);
        
    }//GEN-LAST:event_formWindowOpened

    private void tblAdminChoisirMoniteurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAdminChoisirMoniteurMouseClicked
        // TODO add your handling code here:
        int numMoniteur = Integer.parseInt(tblAdminChoisirMoniteur.getValueAt(tblAdminChoisirMoniteur.getSelectedRow(), 0).toString());
        
        mdl = new ModelJTable();
        mdl.loadDatasPlanningMoniteur(ctrlLecon.GetLeconByIdMoniteur(numMoniteur));
        tblAdminPlanningMoniteur.setModel(mdl);
    }//GEN-LAST:event_tblAdminChoisirMoniteurMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdminMoniteurPlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdminMoniteurPlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdminMoniteurPlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdminMoniteurPlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdminMoniteurPlanning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblChoisirMoniteur;
    private javax.swing.JLabel lblPlanningMoniteur;
    private javax.swing.JLabel lblTitreMoniteur;
    private javax.swing.JTable tblAdminChoisirMoniteur;
    private javax.swing.JTable tblAdminPlanningMoniteur;
    // End of variables declaration//GEN-END:variables
}
