/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controlers.CtrlCategorie;
import Controlers.CtrlVehicule;
import Entities.Categorie;
import Entities.Vehicule;
import javax.swing.JOptionPane;

/**
 *
 * @author Rakotomalala Cédric
 */
public class FrmAdminModifierVehicule extends javax.swing.JFrame {

    CtrlVehicule ctrlVehicule;
    CtrlCategorie ctrlCategorie;
    /**
     * Creates new form FrmAdminAjoutVehicule1
     */
    public FrmAdminModifierVehicule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboModifierCatVehicule = new javax.swing.JComboBox<>();
        lblAjoutCatVehicule = new javax.swing.JLabel();
        ycModifierAnneeVehicule = new com.toedter.calendar.JYearChooser();
        lblModifierAnneeVehicule = new javax.swing.JLabel();
        lblModifierModeleVehicule = new javax.swing.JLabel();
        txtModifierModeleVehicule = new javax.swing.JTextField();
        txtModifierMarque = new javax.swing.JTextField();
        lblModifierMarque = new javax.swing.JLabel();
        lblModifierImmatriculation = new javax.swing.JLabel();
        lblAjoutVehicule = new javax.swing.JLabel();
        btnModifierVehicule = new javax.swing.JButton();
        cboModifierImmatriculation = new javax.swing.JComboBox<>();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblAjoutCatVehicule.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAjoutCatVehicule.setText("La catégorie du véhicule :");

        lblModifierAnneeVehicule.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblModifierAnneeVehicule.setText("L'année du véhicule :");

        lblModifierModeleVehicule.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblModifierModeleVehicule.setText("Le modèle du véhicule : ");

        lblModifierMarque.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblModifierMarque.setText("La marque du véhicule : ");

        lblModifierImmatriculation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblModifierImmatriculation.setText("Immatriculation du véhicule : ");

        lblAjoutVehicule.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAjoutVehicule.setText("Modifier un véhicule");

        btnModifierVehicule.setText("Modifier le véhicule");
        btnModifierVehicule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifierVehiculeMouseClicked(evt);
            }
        });

        cboModifierImmatriculation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboModifierImmatriculationItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblModifierModeleVehicule)
                                    .addComponent(lblModifierAnneeVehicule)
                                    .addComponent(lblAjoutCatVehicule))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtModifierModeleVehicule, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(ycModifierAnneeVehicule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboModifierCatVehicule, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblModifierImmatriculation)
                                    .addComponent(lblModifierMarque))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtModifierMarque, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(cboModifierImmatriculation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(lblAjoutVehicule))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(btnModifierVehicule)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblAjoutVehicule)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModifierImmatriculation)
                    .addComponent(cboModifierImmatriculation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModifierMarque)
                    .addComponent(txtModifierMarque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModifierModeleVehicule)
                    .addComponent(txtModifierModeleVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModifierAnneeVehicule)
                    .addComponent(ycModifierAnneeVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAjoutCatVehicule)
                    .addComponent(cboModifierCatVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnModifierVehicule)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifierVehiculeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifierVehiculeMouseClicked
        if (txtModifierMarque.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Le champ marque ne peut pas être vide !","Modification d'un véhicule",JOptionPane.WARNING_MESSAGE);
        } else if (txtModifierModeleVehicule.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Le champ modèle ne peut pas être vide !","Modification d'un véhicule",JOptionPane.WARNING_MESSAGE);
        } else {
            Vehicule vehicule = new Vehicule(cboModifierImmatriculation.getSelectedItem().toString(), txtModifierMarque.getText(), txtModifierModeleVehicule.getText(), ycModifierAnneeVehicule.getYear(), ctrlCategorie.getIdCategorie(cboModifierCatVehicule.getSelectedItem().toString()));
            ctrlVehicule.editVehicule(vehicule);
            JOptionPane.showMessageDialog(this, "Modification du véhicule a été prise en compte");
        }
    }//GEN-LAST:event_btnModifierVehiculeMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ctrlVehicule = new CtrlVehicule();
        ctrlCategorie = new CtrlCategorie();
        
        for (Vehicule vehicule : ctrlVehicule.getAllVehicule()) {
            cboModifierImmatriculation.addItem(vehicule.getImmatriculation());
        }
        
        for (Categorie categorie : ctrlCategorie.getAllCategorie()) {
            cboModifierCatVehicule.addItem(categorie.getLibelle());
        }
    }//GEN-LAST:event_formWindowOpened

    private void cboModifierImmatriculationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboModifierImmatriculationItemStateChanged
        Vehicule vehicule = ctrlVehicule.getVehicule(cboModifierImmatriculation.getSelectedItem().toString());
        
        txtModifierMarque.setText(vehicule.getMarque());
        txtModifierModeleVehicule.setText(vehicule.getModele());
        ycModifierAnneeVehicule.setYear(vehicule.getAnnee());
        
        for (int i = 0; i < cboModifierCatVehicule.getItemCount(); i++) {
            if (cboModifierCatVehicule.getItemAt(i).equals(ctrlCategorie.getCategorie(vehicule.getCodeCategorie()).getLibelle())) {
                cboModifierCatVehicule.setSelectedIndex(i);
            }
        }
    }//GEN-LAST:event_cboModifierImmatriculationItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdminModifierVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdminModifierVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdminModifierVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdminModifierVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdminModifierVehicule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModifierVehicule;
    private javax.swing.JComboBox<String> cboModifierCatVehicule;
    private javax.swing.JComboBox<String> cboModifierImmatriculation;
    private javax.swing.JLabel lblAjoutCatVehicule;
    private javax.swing.JLabel lblAjoutVehicule;
    private javax.swing.JLabel lblModifierAnneeVehicule;
    private javax.swing.JLabel lblModifierImmatriculation;
    private javax.swing.JLabel lblModifierMarque;
    private javax.swing.JLabel lblModifierModeleVehicule;
    private javax.swing.JTextField txtModifierMarque;
    private javax.swing.JTextField txtModifierModeleVehicule;
    private com.toedter.calendar.JYearChooser ycModifierAnneeVehicule;
    // End of variables declaration//GEN-END:variables
}
