/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

/**
 *
 * @author Rakotomalala Cédric
 */
public class FrmAdminStatsMoniteurEtVehicule extends javax.swing.JFrame {

    /**
     * Creates new form FrmAdminStatsMoniteurEtVehicule
     */
    public FrmAdminStatsMoniteurEtVehicule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUnMoniteurSollicite = new javax.swing.JTable();
        lblUnMoniteurSollicité = new javax.swing.JLabel();
        lblADminStatMoniteurVehicule = new javax.swing.JLabel();
        lblLesMoniteursSollicites = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLesMoniteursSollicites = new javax.swing.JTable();
        btnAdminGraphiqueLesMoniteurs = new javax.swing.JButton();
        lblLesVehiculesSollicites = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblLesVehiculesSollicites = new javax.swing.JTable();
        btnAdminGraphiqueVehicule = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUnVehiculeSollicite = new javax.swing.JTable();
        lblUnVehiculeSollicité = new javax.swing.JLabel();

        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(tblUnMoniteurSollicite);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 95, 558, 353));

        lblUnMoniteurSollicité.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblUnMoniteurSollicité.setText("Le moniteur le plus sollicité");
        getContentPane().add(lblUnMoniteurSollicité, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 70, -1, -1));

        lblADminStatMoniteurVehicule.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblADminStatMoniteurVehicule.setText("Statistiques des moniteurs et véhicules les plus sollicités ");
        getContentPane().add(lblADminStatMoniteurVehicule, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 10, 1061, 30));

        lblLesMoniteursSollicites.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblLesMoniteursSollicites.setText("Classement des moniteurs les plus sollcités");
        getContentPane().add(lblLesMoniteursSollicites, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 70, -1, -1));

        jScrollPane2.setViewportView(tblLesMoniteursSollicites);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 95, 621, 353));

        btnAdminGraphiqueLesMoniteurs.setText("Voir le Graphique des moniteurs");
        btnAdminGraphiqueLesMoniteurs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminGraphiqueLesMoniteursMouseClicked(evt);
            }
        });
        getContentPane().add(btnAdminGraphiqueLesMoniteurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 454, 621, -1));

        lblLesVehiculesSollicites.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblLesVehiculesSollicites.setText("Les véhicules les plus sollicités");
        getContentPane().add(lblLesVehiculesSollicites, new org.netbeans.lib.awtextra.AbsoluteConstraints(774, 495, -1, 16));

        jScrollPane4.setViewportView(tblLesVehiculesSollicites);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 517, 627, -1));

        btnAdminGraphiqueVehicule.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnAdminGraphiqueVehicule.setText("Voir le graphique des véhicules");
        btnAdminGraphiqueVehicule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminGraphiqueVehiculeMouseClicked(evt);
            }
        });
        getContentPane().add(btnAdminGraphiqueVehicule, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 930, 630, -1));

        jScrollPane3.setViewportView(tblUnVehiculeSollicite);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 517, 558, -1));

        lblUnVehiculeSollicité.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblUnVehiculeSollicité.setText("Le véhicule le plus sollicités");
        getContentPane().add(lblUnVehiculeSollicité, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 492, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminGraphiqueVehiculeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminGraphiqueVehiculeMouseClicked
        // TODO add your handling code here:
        FrmAdminGraphiqueVehicule frm= new FrmAdminGraphiqueVehicule();
        frm.setVisible(true);
    }//GEN-LAST:event_btnAdminGraphiqueVehiculeMouseClicked

    private void btnAdminGraphiqueLesMoniteursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminGraphiqueLesMoniteursMouseClicked

        FrmAdminGraphiqueMoniteur frm = new FrmAdminGraphiqueMoniteur();
        frm.setVisible(true);
    }//GEN-LAST:event_btnAdminGraphiqueLesMoniteursMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdminStatsMoniteurEtVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdminStatsMoniteurEtVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdminStatsMoniteurEtVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdminStatsMoniteurEtVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdminStatsMoniteurEtVehicule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminGraphiqueLesMoniteurs;
    private javax.swing.JButton btnAdminGraphiqueVehicule;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblADminStatMoniteurVehicule;
    private javax.swing.JLabel lblLesMoniteursSollicites;
    private javax.swing.JLabel lblLesVehiculesSollicites;
    private javax.swing.JLabel lblUnMoniteurSollicité;
    private javax.swing.JLabel lblUnVehiculeSollicité;
    private javax.swing.JTable tblLesMoniteursSollicites;
    private javax.swing.JTable tblLesVehiculesSollicites;
    private javax.swing.JTable tblUnMoniteurSollicite;
    private javax.swing.JTable tblUnVehiculeSollicite;
    // End of variables declaration//GEN-END:variables
}
