/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controlers.CtrlEleve;
import javax.swing.JOptionPane;

/**
 *
 * @author ninou
 */
public class FrmAdminAjoutMoniteur extends javax.swing.JFrame {

    /**
     * Creates new form FrmEleveInscription
     */
    public FrmAdminAjoutMoniteur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdminAjoutMoniteur = new javax.swing.JLabel();
        lblAjoutMoniteurNom = new javax.swing.JLabel();
        lblAjoutMoniteurPrenom = new javax.swing.JLabel();
        lblAjoutMoniteurDateNaiss = new javax.swing.JLabel();
        lblAjoutMoniteurAdresse = new javax.swing.JLabel();
        lblAjoutMoniteurRue = new javax.swing.JLabel();
        lblAjoutMoniteurCodePostale = new javax.swing.JLabel();
        lblAjoutMoniteurVille = new javax.swing.JLabel();
        lblAjoutMoniteurNumeroTelephone = new javax.swing.JLabel();
        lblAjoutMoniteurSexe = new javax.swing.JLabel();
        btnAjoutMoniteur = new javax.swing.JButton();
        txtAjoutMoniteurNom = new javax.swing.JTextField();
        txtAjoutMoniteurPrenom = new javax.swing.JTextField();
        txtAjoutMoniteurInfoRue = new javax.swing.JTextField();
        txtAjoutMoniteurCodePostale = new javax.swing.JTextField();
        txtAjoutMoniteurVille = new javax.swing.JTextField();
        txtAjoutMoniteurNumeroTelephone = new javax.swing.JTextField();
        dcAjoutMoniteurDateDeNaiss = new com.toedter.calendar.JDateChooser();
        lblAjoutMoniteurLogin = new javax.swing.JLabel();
        txtAjoutMoniteurLogin = new javax.swing.JTextField();
        lblAjoutMoniteurMDP = new javax.swing.JLabel();
        txtAjoutMoniteurMdp = new javax.swing.JTextField();
        cboAjoutMoniteurSexe = new javax.swing.JComboBox<>();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblAdminAjoutMoniteur.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAdminAjoutMoniteur.setText("Ajouter un moniteur");

        lblAjoutMoniteurNom.setText("Nom :");

        lblAjoutMoniteurPrenom.setText("Prénom :");

        lblAjoutMoniteurDateNaiss.setText("Date de naissance :");

        lblAjoutMoniteurAdresse.setText("Adresse :");

        lblAjoutMoniteurRue.setText("Numéro et nom de la rue :");

        lblAjoutMoniteurCodePostale.setText("Code postal :");

        lblAjoutMoniteurVille.setText("Ville :");

        lblAjoutMoniteurNumeroTelephone.setText("Numéro de téléphone :");

        lblAjoutMoniteurSexe.setText("Sexe :");

        btnAjoutMoniteur.setText("Ajouter le moniteur");
        btnAjoutMoniteur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjoutMoniteurMouseClicked(evt);
            }
        });

        lblAjoutMoniteurLogin.setText("Le login du moniteur :");

        lblAjoutMoniteurMDP.setText("Le mot de passe du moniteur :");

        cboAjoutMoniteurSexe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homme", "Femme" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAjoutMoniteurNom, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAjoutMoniteurDateNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAjoutMoniteurAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAjoutMoniteurSexe, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAjoutMoniteurNumeroTelephone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAjoutMoniteurPrenom)
                            .addComponent(lblAjoutMoniteurMDP)
                            .addComponent(lblAjoutMoniteurLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAjoutMoniteurRue, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAjoutMoniteurVille, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAjoutMoniteurCodePostale, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtAjoutMoniteurNom)
                        .addComponent(txtAjoutMoniteurPrenom)
                        .addComponent(txtAjoutMoniteurInfoRue)
                        .addComponent(txtAjoutMoniteurCodePostale)
                        .addComponent(txtAjoutMoniteurVille)
                        .addComponent(txtAjoutMoniteurNumeroTelephone)
                        .addComponent(dcAjoutMoniteurDateDeNaiss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAjoutMoniteurLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                        .addComponent(txtAjoutMoniteurMdp))
                    .addComponent(cboAjoutMoniteurSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblAdminAjoutMoniteur)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAjoutMoniteur)
                        .addGap(142, 142, 142))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAdminAjoutMoniteur)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAjoutMoniteurNom)
                            .addComponent(txtAjoutMoniteurNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAjoutMoniteurPrenom)
                            .addComponent(txtAjoutMoniteurPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAjoutMoniteurDateNaiss))
                    .addComponent(dcAjoutMoniteurDateDeNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAjoutMoniteurAdresse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAjoutMoniteurRue)
                            .addComponent(txtAjoutMoniteurInfoRue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAjoutMoniteurCodePostale)
                            .addComponent(txtAjoutMoniteurCodePostale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAjoutMoniteurVille)
                            .addComponent(txtAjoutMoniteurVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAjoutMoniteurNumeroTelephone)
                            .addComponent(txtAjoutMoniteurNumeroTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblAjoutMoniteurSexe))
                    .addComponent(cboAjoutMoniteurSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAjoutMoniteurLogin)
                    .addComponent(txtAjoutMoniteurLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAjoutMoniteurMDP)
                    .addComponent(txtAjoutMoniteurMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAjoutMoniteur)
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjoutMoniteurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjoutMoniteurMouseClicked
        // TODO add your handling code here:
        if(txtAjoutMoniteurNom.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Saisir un Nom","Choix du nom",JOptionPane.WARNING_MESSAGE);
        }
        else if(dcAjoutMoniteurDateDeNaiss.getDate()== null){
            JOptionPane.showMessageDialog(this, "Sélectionner une Date","Choix de la date",JOptionPane.WARNING_MESSAGE);
        }
        else if(txtAjoutMoniteurPrenom.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Saisir un Prénom","Choix du Prénom",JOptionPane.WARNING_MESSAGE);
        }
        else if(txtAjoutMoniteurInfoRue.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Saisir une adresse","Choix de l'adresse",JOptionPane.WARNING_MESSAGE);
        }
        else if(txtAjoutMoniteurCodePostale.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Saisir un code postale","Choix du Code postale",JOptionPane.WARNING_MESSAGE);
        }
        else if(txtAjoutMoniteurVille.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Saisir une ville","Choix de la ville",JOptionPane.WARNING_MESSAGE);
        }
        else if(txtAjoutMoniteurNumeroTelephone.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Saisir un numéro de téléphone","Choix du numéro",JOptionPane.WARNING_MESSAGE);
        }
        else if(txtAjoutMoniteurLogin.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Saisir un login","Choix du login",JOptionPane.WARNING_MESSAGE);
        }
        else if(txtAjoutMoniteurMdp.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Saisir un mdp","Choix du mdp",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAjoutMoniteurMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdminAjoutMoniteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdminAjoutMoniteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdminAjoutMoniteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdminAjoutMoniteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdminAjoutMoniteur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjoutMoniteur;
    private javax.swing.JComboBox<String> cboAjoutMoniteurSexe;
    private com.toedter.calendar.JDateChooser dcAjoutMoniteurDateDeNaiss;
    private javax.swing.JLabel lblAdminAjoutMoniteur;
    private javax.swing.JLabel lblAjoutMoniteurAdresse;
    private javax.swing.JLabel lblAjoutMoniteurCodePostale;
    private javax.swing.JLabel lblAjoutMoniteurDateNaiss;
    private javax.swing.JLabel lblAjoutMoniteurLogin;
    private javax.swing.JLabel lblAjoutMoniteurMDP;
    private javax.swing.JLabel lblAjoutMoniteurNom;
    private javax.swing.JLabel lblAjoutMoniteurNumeroTelephone;
    private javax.swing.JLabel lblAjoutMoniteurPrenom;
    private javax.swing.JLabel lblAjoutMoniteurRue;
    private javax.swing.JLabel lblAjoutMoniteurSexe;
    private javax.swing.JLabel lblAjoutMoniteurVille;
    private javax.swing.JTextField txtAjoutMoniteurCodePostale;
    private javax.swing.JTextField txtAjoutMoniteurInfoRue;
    private javax.swing.JTextField txtAjoutMoniteurLogin;
    private javax.swing.JTextField txtAjoutMoniteurMdp;
    private javax.swing.JTextField txtAjoutMoniteurNom;
    private javax.swing.JTextField txtAjoutMoniteurNumeroTelephone;
    private javax.swing.JTextField txtAjoutMoniteurPrenom;
    private javax.swing.JTextField txtAjoutMoniteurVille;
    // End of variables declaration//GEN-END:variables
}
