/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controlers.CtrlCategorie;
import Controlers.CtrlLecon;
import Controlers.CtrlMoniteur;
import Controlers.CtrlVehicule;
import Entities.Categorie;
import Entities.Moniteur;
import Entities.Vehicule;

/**
 *
 * @author Rakotomalala Cédric
 */
public class FrmAdminStatsLecons extends javax.swing.JFrame {

    /**
     * Creates new form FrmAdminStatsLecons
     */
    
    CtrlLecon    ctrlLecon;
    CtrlMoniteur ctrlMoniteur;
    CtrlVehicule ctrlVehicule;
    CtrlCategorie ctrlCategorie;
    
    public FrmAdminStatsLecons() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitreStatLecon = new javax.swing.JLabel();
        lblAdminStatLeconMoniteur = new javax.swing.JLabel();
        cboStatMoniteur = new javax.swing.JComboBox<>();
        cboStatVehicule = new javax.swing.JComboBox<>();
        lblAdminStatLeconVehicule = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cboStatCategorie = new javax.swing.JComboBox<>();
        btnAdminStatLecons = new javax.swing.JButton();
        txtNbrLeconMoniteur = new javax.swing.JTextField();
        txtNbrLeconVehicule = new javax.swing.JTextField();
        txtNbrLeconCategorie = new javax.swing.JTextField();
        lblNombreCategorie = new javax.swing.JLabel();
        lblNombreVehicule = new javax.swing.JLabel();
        lblNombreLeconMoniteur = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblTitreStatLecon.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblTitreStatLecon.setText("Le nombre de leçons ");

        lblAdminStatLeconMoniteur.setText("Choisissez un moniteur");

        lblAdminStatLeconVehicule.setText("Choisissez un vehicule");

        jLabel1.setText("Choisissez une catégorie");

        btnAdminStatLecons.setText("Voir le nombre de leçons");
        btnAdminStatLecons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminStatLeconsMouseClicked(evt);
            }
        });

        txtNbrLeconMoniteur.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNbrLeconMoniteur.setEnabled(false);

        txtNbrLeconVehicule.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNbrLeconVehicule.setEnabled(false);

        txtNbrLeconCategorie.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNbrLeconCategorie.setEnabled(false);

        lblNombreCategorie.setText("Le nombre de leçons pour cette catégorie est de :");

        lblNombreVehicule.setText("Le nombre de fois que ce véhicule à été choisis est de :");

        lblNombreLeconMoniteur.setText("Le nombre de fois que ce moniteur à été pris est de:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombreVehicule)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNbrLeconVehicule, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombreLeconMoniteur)
                        .addGap(21, 21, 21)
                        .addComponent(txtNbrLeconMoniteur))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdminStatLecons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(lblAdminStatLeconVehicule)
                                    .addComponent(lblAdminStatLeconMoniteur))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboStatCategorie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboStatVehicule, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboStatMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombreCategorie)
                        .addGap(34, 34, 34)
                        .addComponent(txtNbrLeconCategorie)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitreStatLecon)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitreStatLecon)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminStatLeconMoniteur)
                    .addComponent(cboStatMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminStatLeconVehicule)
                    .addComponent(cboStatVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboStatCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addComponent(btnAdminStatLecons)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreLeconMoniteur)
                    .addComponent(txtNbrLeconMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreVehicule)
                    .addComponent(txtNbrLeconVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNbrLeconCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreCategorie))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ctrlLecon= new CtrlLecon();
        ctrlMoniteur = new CtrlMoniteur();
        ctrlVehicule = new CtrlVehicule();
        ctrlCategorie = new CtrlCategorie();
        
        for(Moniteur unMoniteur : ctrlMoniteur.GetAllMoniteur()){
            cboStatMoniteur.addItem(unMoniteur.getNom());
        }
        for(Vehicule unVehicule : ctrlVehicule.getAllVehicule()){
            cboStatVehicule.addItem(unVehicule.getImmatriculation());
        }
        
        for (Categorie cat : ctrlCategorie.getAllCategorie()){
            cboStatCategorie.addItem(cat.getLibelle());
        }
          
        
    }//GEN-LAST:event_formWindowOpened

    private void btnAdminStatLeconsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminStatLeconsMouseClicked
        // TODO add your handling code here:
        
        txtNbrLeconMoniteur.setText(String.valueOf(ctrlLecon.getNombreDeLeconMoniteur(ctrlMoniteur.getIdMoniteurByName(cboStatMoniteur.getSelectedItem().toString())) ));
        txtNbrLeconVehicule.setText(String.valueOf(ctrlLecon.getNombreDeLeconVehicule(cboStatVehicule.getSelectedItem().toString())));
        txtNbrLeconCategorie.setText(String.valueOf(ctrlLecon.getNombreDeLeconCategorie(ctrlCategorie.getIdCategorie(cboStatCategorie.getSelectedItem().toString()))));
        
    }//GEN-LAST:event_btnAdminStatLeconsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdminStatsLecons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdminStatsLecons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdminStatsLecons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdminStatsLecons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdminStatsLecons().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminStatLecons;
    private javax.swing.JComboBox<String> cboStatCategorie;
    private javax.swing.JComboBox<String> cboStatMoniteur;
    private javax.swing.JComboBox<String> cboStatVehicule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAdminStatLeconMoniteur;
    private javax.swing.JLabel lblAdminStatLeconVehicule;
    private javax.swing.JLabel lblNombreCategorie;
    private javax.swing.JLabel lblNombreLeconMoniteur;
    private javax.swing.JLabel lblNombreVehicule;
    private javax.swing.JLabel lblTitreStatLecon;
    private javax.swing.JTextField txtNbrLeconCategorie;
    private javax.swing.JTextField txtNbrLeconMoniteur;
    private javax.swing.JTextField txtNbrLeconVehicule;
    // End of variables declaration//GEN-END:variables
}
