/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controlers.CtrlEleve;
import Entities.Eleve;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author ninou
 */
public class FrmEleveModificationInformation extends javax.swing.JFrame {

    /**
     * Creates new form FrmEleveModificationInformation
     */
    CtrlEleve ctrlEleve;
    static Eleve eleve;
    public FrmEleveModificationInformation() {
        initComponents();
    }
    public FrmEleveModificationInformation(Eleve unEleve) {
        initComponents();
        eleve=unEleve;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEleveModifInformations = new javax.swing.JButton();
        lblEleveModifTitre = new javax.swing.JLabel();
        txtEleveModifNom = new javax.swing.JTextField();
        lblEleveModifNom = new javax.swing.JLabel();
        txtEleveModifPrenom = new javax.swing.JTextField();
        lblEleveModifPrenom = new javax.swing.JLabel();
        txtEleveModifInfoRue = new javax.swing.JTextField();
        lblEleveModifDateDeNaissance = new javax.swing.JLabel();
        txtEleveModifVille = new javax.swing.JTextField();
        lblEleveModifRue = new javax.swing.JLabel();
        txtEleveModifNumeroTelephone = new javax.swing.JTextField();
        lblEleveModifCodePostale = new javax.swing.JLabel();
        lblEleveModifVille = new javax.swing.JLabel();
        dcEleveModifDateNaissance = new com.toedter.calendar.JDateChooser();
        txtEleveModifCodePostale = new javax.swing.JTextField();
        lblEleveModifNumeroTelephone = new javax.swing.JLabel();
        lblEleveModifAdresse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnEleveModifInformations.setText("Modifier mes informations");
        btnEleveModifInformations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEleveModifInformationsMouseClicked(evt);
            }
        });

        lblEleveModifTitre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEleveModifTitre.setText("Modifier mes informations personnelles ");

        lblEleveModifNom.setText("Nom :");

        lblEleveModifPrenom.setText("Prénom :");

        lblEleveModifDateDeNaissance.setText("Date de naissance :");

        lblEleveModifRue.setText("Numéro et nom de la rue :");

        lblEleveModifCodePostale.setText("Code postal :");

        lblEleveModifVille.setText("Ville :");

        lblEleveModifNumeroTelephone.setText("Numéro de téléphone :");

        lblEleveModifAdresse.setText("Adresse :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addComponent(lblEleveModifTitre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEleveModifNom, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEleveModifDateDeNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEleveModifAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEleveModifNumeroTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEleveModifPrenom)
                            .addComponent(lblEleveModifRue, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEleveModifCodePostale, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEleveModifVille, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEleveModifNom)
                            .addComponent(txtEleveModifPrenom)
                            .addComponent(txtEleveModifInfoRue)
                            .addComponent(txtEleveModifCodePostale)
                            .addComponent(txtEleveModifVille)
                            .addComponent(txtEleveModifNumeroTelephone)
                            .addComponent(dcEleveModifDateNaissance, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(btnEleveModifInformations)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblEleveModifTitre)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEleveModifNom)
                            .addComponent(txtEleveModifNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEleveModifPrenom)
                            .addComponent(txtEleveModifPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEleveModifDateDeNaissance))
                    .addComponent(dcEleveModifDateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEleveModifAdresse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEleveModifRue)
                    .addComponent(txtEleveModifInfoRue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEleveModifCodePostale)
                    .addComponent(txtEleveModifCodePostale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEleveModifVille)
                    .addComponent(txtEleveModifVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEleveModifNumeroTelephone)
                    .addComponent(txtEleveModifNumeroTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEleveModifInformations)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEleveModifInformationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEleveModifInformationsMouseClicked
        // TODO add your handling code here:
         if(txtEleveModifNom.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Saisir un Nom","Choix du nom",JOptionPane.WARNING_MESSAGE);
        }
        else if(dcEleveModifDateNaissance.getDate()== null){
            JOptionPane.showMessageDialog(this, "Sélectionner une Date","Choix de la date",JOptionPane.WARNING_MESSAGE);
        }
        else if(txtEleveModifPrenom.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Saisir un Prénom","Choix du Prénom",JOptionPane.WARNING_MESSAGE);
        }
        else if(txtEleveModifInfoRue.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Saisir une adresse","Choix de l'adresse",JOptionPane.WARNING_MESSAGE);
        }
        else if(txtEleveModifCodePostale.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Saisir un code postale","Choix du Code postale",JOptionPane.WARNING_MESSAGE);
        }
        else if(txtEleveModifVille.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Saisir une ville","Choix de la ville",JOptionPane.WARNING_MESSAGE);
        }
        else if(txtEleveModifNumeroTelephone.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Saisir un numéro de téléphone","Choix du numéro",JOptionPane.WARNING_MESSAGE);
        }
        else {
          SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
          String dateNaiss = sdf.format(dcEleveModifDateNaissance.getDate());
          
          ctrlEleve.modifierEleve(eleve.getNumEleve(),txtEleveModifNom.getText(), txtEleveModifPrenom.getText(), dateNaiss, txtEleveModifInfoRue.getText(), Integer.parseInt(txtEleveModifCodePostale.getText()) , txtEleveModifVille.getText(), txtEleveModifNumeroTelephone.getText());
          JOptionPane.showMessageDialog(this, "Votre modification est faite");
        }
    }//GEN-LAST:event_btnEleveModifInformationsMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ctrlEleve = new CtrlEleve();
        txtEleveModifNom.setText(eleve.getNom());
        txtEleveModifPrenom.setText(eleve.getPrenom());
        dcEleveModifDateNaissance.setDate(eleve.getDateDeNaissance());
        txtEleveModifInfoRue.setText(eleve.getAdresse1());
        txtEleveModifCodePostale.setText(String.valueOf(eleve.getCodePostal()));
        txtEleveModifNumeroTelephone.setText(eleve.getTelephone());
        txtEleveModifVille.setText(eleve.getVille());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEleveModificationInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEleveModificationInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEleveModificationInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEleveModificationInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEleveModificationInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEleveModifInformations;
    private com.toedter.calendar.JDateChooser dcEleveModifDateNaissance;
    private javax.swing.JLabel lblEleveModifAdresse;
    private javax.swing.JLabel lblEleveModifCodePostale;
    private javax.swing.JLabel lblEleveModifDateDeNaissance;
    private javax.swing.JLabel lblEleveModifNom;
    private javax.swing.JLabel lblEleveModifNumeroTelephone;
    private javax.swing.JLabel lblEleveModifPrenom;
    private javax.swing.JLabel lblEleveModifRue;
    private javax.swing.JLabel lblEleveModifTitre;
    private javax.swing.JLabel lblEleveModifVille;
    private javax.swing.JTextField txtEleveModifCodePostale;
    private javax.swing.JTextField txtEleveModifInfoRue;
    private javax.swing.JTextField txtEleveModifNom;
    private javax.swing.JTextField txtEleveModifNumeroTelephone;
    private javax.swing.JTextField txtEleveModifPrenom;
    private javax.swing.JTextField txtEleveModifVille;
    // End of variables declaration//GEN-END:variables
}
