/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controlers.CtrlEleve;
import Entities.Eleve;
import Tools.ConnexionBDD;
import javax.swing.JOptionPane;

/**
 *
 * @author ninou
 */
public class FrmEleveConnexion extends javax.swing.JFrame {

    /**
     * Creates new form frmEleveConnexion
     */
    ConnexionBDD maCnx;
    CtrlEleve ctrlEleve;
    
    public FrmEleveConnexion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEleveTitre = new javax.swing.JLabel();
        lblEleveConnexion = new javax.swing.JLabel();
        lblEleveIdentifiant = new javax.swing.JLabel();
        lblEleveMotDePasse = new javax.swing.JLabel();
        txtEleveIdentifiant = new javax.swing.JTextField();
        btnEleveConnexion = new javax.swing.JButton();
        btnEleveSinscrire = new javax.swing.JButton();
        btnEleveRetourConnexion = new javax.swing.JButton();
        pfEleveMotDePasse = new javax.swing.JPasswordField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblEleveTitre.setText("LeRebours-auto");

        lblEleveConnexion.setText("Connexion à l'espace élève");

        lblEleveIdentifiant.setText("Identifiant :");

        lblEleveMotDePasse.setText("Mot de passe :");

        btnEleveConnexion.setText("Connexion");
        btnEleveConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEleveConnexionActionPerformed(evt);
            }
        });

        btnEleveSinscrire.setText("S'inscrire ");
        btnEleveSinscrire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEleveSinscrireMouseClicked(evt);
            }
        });

        btnEleveRetourConnexion.setText("Retour");
        btnEleveRetourConnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEleveRetourConnexionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(lblEleveTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblEleveConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEleveConnexion)
                        .addGap(157, 157, 157))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnEleveRetourConnexion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEleveSinscrire)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEleveIdentifiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEleveMotDePasse, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEleveIdentifiant, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(pfEleveMotDePasse))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblEleveTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEleveConnexion)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEleveIdentifiant)
                    .addComponent(txtEleveIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEleveMotDePasse)
                    .addComponent(pfEleveMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btnEleveConnexion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEleveSinscrire)
                    .addComponent(btnEleveRetourConnexion))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEleveRetourConnexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEleveRetourConnexionMouseClicked
        FrmPrincipal frm = new FrmPrincipal();
        frm.setVisible(true);
    }//GEN-LAST:event_btnEleveRetourConnexionMouseClicked

    private void btnEleveSinscrireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEleveSinscrireMouseClicked
        FrmEleveInscription frm = new FrmEleveInscription();
        frm.setVisible(true);
    }//GEN-LAST:event_btnEleveSinscrireMouseClicked

    private void btnEleveConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEleveConnexionActionPerformed
        // TODO add your handling code here:
        if(txtEleveIdentifiant.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Veuillez Saisir un login","Choix du login",JOptionPane.WARNING_MESSAGE);
        }
        else if(pfEleveMotDePasse.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Veuillez Saisir un un mot de passe","Choix du MDP",JOptionPane.WARNING_MESSAGE);
        }
        else {
            Eleve unEleve = ctrlEleve.verifEleve(txtEleveIdentifiant.getText(), pfEleveMotDePasse.getText());
            if(unEleve==null){
                
                JOptionPane.showMessageDialog(null, "Veuillez Saisir des identifiants correctes","Login incorrect",JOptionPane.WARNING_MESSAGE);
            }
            else{
                FrmEleveAcceuil frm= new FrmEleveAcceuil(unEleve);
                frm.setVisible(true);
                
            }
        }
//        FrmEleveAcceuil frm= new FrmEleveAcceuil();
//        frm.setVisible(true);
    }//GEN-LAST:event_btnEleveConnexionActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        maCnx= new ConnexionBDD();
        ctrlEleve= new CtrlEleve();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the commtxtEleveIdentifiantnts
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEleveConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEleveConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEleveConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEleveConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEleveConnexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEleveConnexion;
    private javax.swing.JButton btnEleveRetourConnexion;
    private javax.swing.JButton btnEleveSinscrire;
    private javax.swing.JLabel lblEleveConnexion;
    private javax.swing.JLabel lblEleveIdentifiant;
    private javax.swing.JLabel lblEleveMotDePasse;
    private javax.swing.JLabel lblEleveTitre;
    private javax.swing.JPasswordField pfEleveMotDePasse;
    private javax.swing.JTextField txtEleveIdentifiant;
    // End of variables declaration//GEN-END:variables
}
