/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controlers.CtrlMoniteur;
import Entities.Moniteur;
import Tools.ConnexionBDD;
import javax.swing.JOptionPane;

/**
 *
 * @author ninou
 */
public class FrmMoniteurConnexion extends javax.swing.JFrame {

    CtrlMoniteur ctrlMoniteur;
    ConnexionBDD maCnx;
    /**
     * Creates new form frmMoniteurConnexion
     */
    public FrmMoniteurConnexion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMoniteurMotDePasse = new javax.swing.JLabel();
        txtMoniteurIdentifiant = new javax.swing.JTextField();
        btnMoniteurConnexion = new javax.swing.JButton();
        btnMoniteurSinscrire = new javax.swing.JButton();
        lblMoniteurTitre = new javax.swing.JLabel();
        lblMoniteurConnexion = new javax.swing.JLabel();
        lblMoniteurIdentifiant = new javax.swing.JLabel();
        btnMoniteurRetourConnexion = new javax.swing.JButton();
        pfMoniteurMotDePasse = new javax.swing.JPasswordField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblMoniteurMotDePasse.setText("Mot de passe :");

        btnMoniteurConnexion.setText("Connexion");
        btnMoniteurConnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMoniteurConnexionMouseClicked(evt);
            }
        });

        btnMoniteurSinscrire.setText("S'inscrire ");

        lblMoniteurTitre.setText("LeRebours-auto");

        lblMoniteurConnexion.setText("Connexion à l'espace moniteur");

        lblMoniteurIdentifiant.setText("Identifiant :");

        btnMoniteurRetourConnexion.setText("Retour");
        btnMoniteurRetourConnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMoniteurRetourConnexionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblMoniteurTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblMoniteurMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pfMoniteurMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMoniteurConnexion)
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMoniteurConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMoniteurIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMoniteurIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(113, 113, 113))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnMoniteurRetourConnexion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMoniteurSinscrire)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblMoniteurTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMoniteurConnexion)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMoniteurIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMoniteurIdentifiant))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMoniteurMotDePasse)
                    .addComponent(pfMoniteurMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnMoniteurConnexion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMoniteurSinscrire)
                    .addComponent(btnMoniteurRetourConnexion))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoniteurRetourConnexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoniteurRetourConnexionMouseClicked
        FrmPrincipal frm = new FrmPrincipal();
        frm.setVisible(true);
    }//GEN-LAST:event_btnMoniteurRetourConnexionMouseClicked

    private void btnMoniteurConnexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoniteurConnexionMouseClicked
        if(txtMoniteurIdentifiant.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Veuillez Saisir un login","Choix du login",JOptionPane.WARNING_MESSAGE);
        }
        else if(pfMoniteurMotDePasse.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Veuillez Saisir un un mot de passe","Choix du MDP",JOptionPane.WARNING_MESSAGE);
        }
        else {
            Moniteur unMoniteur = ctrlMoniteur.verifMoniteur(txtMoniteurIdentifiant.getText(), pfMoniteurMotDePasse.getText());
            if(unMoniteur==null){
                
                JOptionPane.showMessageDialog(null, "Veuillez Saisir des identifiants correctes","Login incorrect",JOptionPane.WARNING_MESSAGE);
            }
            else{
                FrmMoniteurAcceuil frm= new FrmMoniteurAcceuil(unMoniteur);
                frm.setVisible(true);
                
            }
        }
    }//GEN-LAST:event_btnMoniteurConnexionMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        maCnx= new ConnexionBDD();
        ctrlMoniteur= new CtrlMoniteur();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMoniteurConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMoniteurConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMoniteurConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMoniteurConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMoniteurConnexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoniteurConnexion;
    private javax.swing.JButton btnMoniteurRetourConnexion;
    private javax.swing.JButton btnMoniteurSinscrire;
    private javax.swing.JLabel lblMoniteurConnexion;
    private javax.swing.JLabel lblMoniteurIdentifiant;
    private javax.swing.JLabel lblMoniteurMotDePasse;
    private javax.swing.JLabel lblMoniteurTitre;
    private javax.swing.JPasswordField pfMoniteurMotDePasse;
    private javax.swing.JTextField txtMoniteurIdentifiant;
    // End of variables declaration//GEN-END:variables
}
