/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controlers.CtrlMoniteur;
import Entities.Moniteur;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author ninou
 */
public class FrmMoniteurModifierInformation extends javax.swing.JFrame {

    /**
     * Creates new form FrmMoniteurModifierInformations
     */
     static Moniteur unMoniteur;
     CtrlMoniteur ctrlMoniteur;
    public FrmMoniteurModifierInformation() {
        initComponents();
    }
    public FrmMoniteurModifierInformation(Moniteur unMoniteur) {
        initComponents();
        this.unMoniteur = unMoniteur;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMoniteurModifVille = new javax.swing.JTextField();
        lblMoniteurModifRue = new javax.swing.JLabel();
        txtMoniteurModifNumeroTelephone = new javax.swing.JTextField();
        lblMoniteurModifCodePostale = new javax.swing.JLabel();
        lblMoniteurModifVille = new javax.swing.JLabel();
        dcMoniteurModifDateNaissance = new com.toedter.calendar.JDateChooser();
        lblMoniteurModifNumeroTelephone = new javax.swing.JLabel();
        btnMoniteurModifInformations = new javax.swing.JButton();
        lblMoniteurModifTitre = new javax.swing.JLabel();
        txtMoniteurModifNom = new javax.swing.JTextField();
        lblMoniteurModifNom = new javax.swing.JLabel();
        txtMoniteurModifPrenom = new javax.swing.JTextField();
        lblMoniteurModifPrenom = new javax.swing.JLabel();
        txtMoniteurModifInfoRue = new javax.swing.JTextField();
        lblMoniteurModifDateDeNaissance = new javax.swing.JLabel();
        txtMoniteurModifCodePostale = new javax.swing.JTextField();
        lblMoniteurModifAdresse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblMoniteurModifRue.setText("Numéro et nom de la rue :");

        lblMoniteurModifCodePostale.setText("Code postale :");

        lblMoniteurModifVille.setText("Ville :");

        lblMoniteurModifNumeroTelephone.setText("Numéro de téléphone :");

        btnMoniteurModifInformations.setText("Modifier mes informations");
        btnMoniteurModifInformations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMoniteurModifInformationsMouseClicked(evt);
            }
        });

        lblMoniteurModifTitre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMoniteurModifTitre.setText("Modifier mes informations personnelles ");

        lblMoniteurModifNom.setText("Nom :");

        lblMoniteurModifPrenom.setText("Prénom :");

        lblMoniteurModifDateDeNaissance.setText("Date de naissance :");

        lblMoniteurModifAdresse.setText("Adresse :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblMoniteurModifTitre))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMoniteurModifNom, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMoniteurModifDateDeNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMoniteurModifAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMoniteurModifNumeroTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMoniteurModifPrenom)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMoniteurModifRue, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMoniteurModifVille, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMoniteurModifCodePostale, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMoniteurModifNom)
                            .addComponent(txtMoniteurModifPrenom)
                            .addComponent(txtMoniteurModifInfoRue)
                            .addComponent(txtMoniteurModifCodePostale)
                            .addComponent(txtMoniteurModifVille)
                            .addComponent(txtMoniteurModifNumeroTelephone)
                            .addComponent(dcMoniteurModifDateNaissance, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnMoniteurModifInformations)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblMoniteurModifTitre)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMoniteurModifNom)
                            .addComponent(txtMoniteurModifNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMoniteurModifPrenom)
                            .addComponent(txtMoniteurModifPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMoniteurModifDateDeNaissance))
                    .addComponent(dcMoniteurModifDateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMoniteurModifAdresse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMoniteurModifRue)
                    .addComponent(txtMoniteurModifInfoRue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMoniteurModifCodePostale)
                    .addComponent(txtMoniteurModifCodePostale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMoniteurModifVille)
                    .addComponent(txtMoniteurModifVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMoniteurModifNumeroTelephone)
                    .addComponent(txtMoniteurModifNumeroTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnMoniteurModifInformations)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoniteurModifInformationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoniteurModifInformationsMouseClicked
        // TODO add your handling code here:
        
        if(txtMoniteurModifNom.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Saisir un Nom","Choix du nom",JOptionPane.WARNING_MESSAGE);
        }
        else if(dcMoniteurModifDateNaissance.getDate()== null){
            JOptionPane.showMessageDialog(this, "Sélectionner une Date","Choix de la date",JOptionPane.WARNING_MESSAGE);
        }
        else if(txtMoniteurModifPrenom.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Saisir un Prénom","Choix du Prénom",JOptionPane.WARNING_MESSAGE);
        }
        else if(txtMoniteurModifInfoRue.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Saisir une adresse","Choix de l'adresse",JOptionPane.WARNING_MESSAGE);
        }
        else if(txtMoniteurModifCodePostale.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Saisir un code postale","Choix du Code postale",JOptionPane.WARNING_MESSAGE);
        }
        else if(txtMoniteurModifVille.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Saisir une ville","Choix de la ville",JOptionPane.WARNING_MESSAGE);
        }
        else if(txtMoniteurModifNumeroTelephone.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez Saisir un numéro de téléphone","Choix du numéro",JOptionPane.WARNING_MESSAGE);
        }
        else {
          SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
          String dateNaiss = sdf.format(dcMoniteurModifDateNaissance.getDate());
          
          ctrlMoniteur.modifierMoniteur(unMoniteur.getCodeMoniteur(),txtMoniteurModifNom.getText(), txtMoniteurModifPrenom.getText(), dateNaiss, txtMoniteurModifInfoRue.getText(), Integer.parseInt(txtMoniteurModifCodePostale.getText()) , txtMoniteurModifVille.getText(), txtMoniteurModifNumeroTelephone.getText());
          JOptionPane.showMessageDialog(this, "Votre modification est faite");
        }
    }//GEN-LAST:event_btnMoniteurModifInformationsMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ctrlMoniteur = new CtrlMoniteur();
        txtMoniteurModifNom.setText(unMoniteur.getNom());
        txtMoniteurModifPrenom.setText(unMoniteur.getPrenom());
        dcMoniteurModifDateNaissance.setDate(unMoniteur.getDateDeNaissance());
        txtMoniteurModifInfoRue.setText(unMoniteur.getAdresse());
        txtMoniteurModifCodePostale.setText(String.valueOf(unMoniteur.getCodePostal()));
        txtMoniteurModifNumeroTelephone.setText(unMoniteur.getTelephone());
        txtMoniteurModifVille.setText(unMoniteur.getVille());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMoniteurModifierInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMoniteurModifierInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMoniteurModifierInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMoniteurModifierInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMoniteurModifierInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoniteurModifInformations;
    private com.toedter.calendar.JDateChooser dcMoniteurModifDateNaissance;
    private javax.swing.JLabel lblMoniteurModifAdresse;
    private javax.swing.JLabel lblMoniteurModifCodePostale;
    private javax.swing.JLabel lblMoniteurModifDateDeNaissance;
    private javax.swing.JLabel lblMoniteurModifNom;
    private javax.swing.JLabel lblMoniteurModifNumeroTelephone;
    private javax.swing.JLabel lblMoniteurModifPrenom;
    private javax.swing.JLabel lblMoniteurModifRue;
    private javax.swing.JLabel lblMoniteurModifTitre;
    private javax.swing.JLabel lblMoniteurModifVille;
    private javax.swing.JTextField txtMoniteurModifCodePostale;
    private javax.swing.JTextField txtMoniteurModifInfoRue;
    private javax.swing.JTextField txtMoniteurModifNom;
    private javax.swing.JTextField txtMoniteurModifNumeroTelephone;
    private javax.swing.JTextField txtMoniteurModifPrenom;
    private javax.swing.JTextField txtMoniteurModifVille;
    // End of variables declaration//GEN-END:variables
}
