/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controlers.CtrlCategorie;
import Controlers.CtrlMoniteur;
import Entities.Categorie;
import Entities.Moniteur;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author ninou
 */
public class FrmMoniteurAjoutLicence extends javax.swing.JFrame {

    CtrlCategorie ctrlCategorie;
    CtrlMoniteur ctrlMoniteur;
    Moniteur unMoniteur;
    /**
     * Creates new form FrmMoniteurAjoutLicence
     */
    public FrmMoniteurAjoutLicence() {
        initComponents();
    }
    
    public FrmMoniteurAjoutLicence(Moniteur unMoniteur) {
        initComponents();
        this.unMoniteur = unMoniteur;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblmoniteurAjoutLicence = new javax.swing.JLabel();
        lblMoniteurCategoriePermis = new javax.swing.JLabel();
        lblMoniteurDateObtention = new javax.swing.JLabel();
        cboMoniteurCategoriePermis = new javax.swing.JComboBox<>();
        dcMoniteurDateObtention = new com.toedter.calendar.JDateChooser();
        btnMoniteurAjoutLicence = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblmoniteurAjoutLicence.setText("Ajouter une licence ");

        lblMoniteurCategoriePermis.setText("Catégorie de permis :");

        lblMoniteurDateObtention.setText("Date d'obtention :");

        btnMoniteurAjoutLicence.setText("Ajouter la licence");
        btnMoniteurAjoutLicence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMoniteurAjoutLicenceMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(lblmoniteurAjoutLicence, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMoniteurCategoriePermis, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMoniteurDateObtention, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dcMoniteurDateObtention, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(cboMoniteurCategoriePermis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnMoniteurAjoutLicence)
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblmoniteurAjoutLicence)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMoniteurCategoriePermis)
                    .addComponent(cboMoniteurCategoriePermis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMoniteurDateObtention)
                    .addComponent(dcMoniteurDateObtention, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnMoniteurAjoutLicence)
                .addGap(47, 47, 47))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ctrlCategorie = new CtrlCategorie();
        ctrlMoniteur = new CtrlMoniteur();
        
        for (Categorie cat : ctrlCategorie.getCategorieNotMoniteur(unMoniteur.getCodeMoniteur())){
            cboMoniteurCategoriePermis.addItem(cat.getLibelle());
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnMoniteurAjoutLicenceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoniteurAjoutLicenceMouseClicked
        if (dcMoniteurDateObtention.getDate().toString().equals("")){
            JOptionPane.showMessageDialog(null, "Sélectionner une Date","Choix de la date",JOptionPane.WARNING_MESSAGE);
        }
        
        else {
            int numLicence = ctrlMoniteur.recupDernierIdLicence();
            int numMoniteur = unMoniteur.getCodeMoniteur();
            int numCategorie = ctrlCategorie.getIdCategorie(cboMoniteurCategoriePermis.getSelectedItem().toString());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dateObtention = sdf.format(dcMoniteurDateObtention.getDate());
            if (ctrlMoniteur.trouverLicenceMoniteur(numMoniteur, numCategorie) ==true){
                JOptionPane.showMessageDialog(this, "Vous possedez déjà cette licence");
               }
            else{
                ctrlMoniteur.ajoutLicenceMoniteur(numLicence, numMoniteur, numCategorie, dateObtention);
                JOptionPane.showMessageDialog(this, "Licence ajoutée");
            }
        }
    }//GEN-LAST:event_btnMoniteurAjoutLicenceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMoniteurAjoutLicence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMoniteurAjoutLicence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMoniteurAjoutLicence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMoniteurAjoutLicence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMoniteurAjoutLicence().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoniteurAjoutLicence;
    private javax.swing.JComboBox<String> cboMoniteurCategoriePermis;
    private com.toedter.calendar.JDateChooser dcMoniteurDateObtention;
    private javax.swing.JLabel lblMoniteurCategoriePermis;
    private javax.swing.JLabel lblMoniteurDateObtention;
    private javax.swing.JLabel lblmoniteurAjoutLicence;
    // End of variables declaration//GEN-END:variables
}
