/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Entities.Moniteur;

/**
 *
 * @author ninou
 */
public class FrmMoniteurAcceuil extends javax.swing.JFrame {

    /**
     * Creates new form FrmMoniteurAcceuil
     */
    static Moniteur unMoniteur;
    public FrmMoniteurAcceuil() {
        initComponents();
    }
      public FrmMoniteurAcceuil(Moniteur unMoniteur) {
        initComponents();
        this.unMoniteur = unMoniteur;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMoniteurNomConnexion = new javax.swing.JLabel();
        btnMoniteurLicence = new javax.swing.JButton();
        btnMoniteurplanning = new javax.swing.JButton();
        btnMoniteurCAetLecon = new javax.swing.JButton();
        txtMoniteurNomConnexion = new javax.swing.JScrollPane();
        txtMoniteurConnecte = new javax.swing.JTextPane();
        btnMoniteurModifierInformation = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnGraphCA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblMoniteurNomConnexion.setText("Vous êtes connecté en tant que  :");

        btnMoniteurLicence.setText("Ajouter une licence ");
        btnMoniteurLicence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMoniteurLicenceMouseClicked(evt);
            }
        });

        btnMoniteurplanning.setText("Visualiser mon planning ");
        btnMoniteurplanning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMoniteurplanningMouseClicked(evt);
            }
        });

        btnMoniteurCAetLecon.setText("Voir son chiffre d'affaires");
        btnMoniteurCAetLecon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMoniteurCAetLeconMouseClicked(evt);
            }
        });
        btnMoniteurCAetLecon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoniteurCAetLeconActionPerformed(evt);
            }
        });

        txtMoniteurConnecte.setEditable(false);
        txtMoniteurNomConnexion.setViewportView(txtMoniteurConnecte);

        btnMoniteurModifierInformation.setText("Modifier mes informations personnelles");
        btnMoniteurModifierInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMoniteurModifierInformationMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ESPACE MONITEUR");

        btnGraphCA.setText("Voir l'évolution de mon chiffre d'affaires");
        btnGraphCA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGraphCAMouseClicked(evt);
            }
        });
        btnGraphCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraphCAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMoniteurModifierInformation)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblMoniteurNomConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMoniteurNomConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMoniteurLicence, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMoniteurplanning, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMoniteurCAetLecon, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGraphCA)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMoniteurNomConnexion)
                    .addComponent(txtMoniteurNomConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnMoniteurplanning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMoniteurLicence)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMoniteurCAetLecon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnGraphCA)
                .addGap(18, 18, 18)
                .addComponent(btnMoniteurModifierInformation)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoniteurLicenceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoniteurLicenceMouseClicked
        FrmMoniteurAjoutLicence frm = new FrmMoniteurAjoutLicence(unMoniteur);
        frm.setVisible(true);
    }//GEN-LAST:event_btnMoniteurLicenceMouseClicked

    private void btnMoniteurplanningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoniteurplanningMouseClicked
        // TODO add your handling code here:
        FrmMoniteurPlanning frm = new FrmMoniteurPlanning(unMoniteur);
        frm.setVisible(true);
    }//GEN-LAST:event_btnMoniteurplanningMouseClicked

    private void btnMoniteurCAetLeconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoniteurCAetLeconMouseClicked
        FrmMoniteurCAetLecon frm = new FrmMoniteurCAetLecon(unMoniteur);
        frm.setVisible(true);
    }//GEN-LAST:event_btnMoniteurCAetLeconMouseClicked

    private void btnMoniteurModifierInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoniteurModifierInformationMouseClicked
        // TODO add your handling code here:
        FrmMoniteurModifierInformation frm = new FrmMoniteurModifierInformation(unMoniteur);
        frm.setVisible(true);
    }//GEN-LAST:event_btnMoniteurModifierInformationMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txtMoniteurConnecte.setText(unMoniteur.getNom() + " " + unMoniteur.getPrenom());
        txtMoniteurConnecte.setEditable(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnGraphCAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGraphCAMouseClicked
        // TODO add your handling code here:
        FrmMoniteurGraphique frm = new FrmMoniteurGraphique(unMoniteur);
        frm.setVisible(true);
    }//GEN-LAST:event_btnGraphCAMouseClicked

    private void btnGraphCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraphCAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGraphCAActionPerformed

    private void btnMoniteurCAetLeconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoniteurCAetLeconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMoniteurCAetLeconActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMoniteurAcceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMoniteurAcceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMoniteurAcceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMoniteurAcceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMoniteurAcceuil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraphCA;
    private javax.swing.JButton btnMoniteurCAetLecon;
    private javax.swing.JButton btnMoniteurLicence;
    private javax.swing.JButton btnMoniteurModifierInformation;
    private javax.swing.JButton btnMoniteurplanning;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMoniteurNomConnexion;
    private javax.swing.JTextPane txtMoniteurConnecte;
    private javax.swing.JScrollPane txtMoniteurNomConnexion;
    // End of variables declaration//GEN-END:variables
}
